remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: Yutong Sun
description: The page of Yutong Sun's STATS201 Introduction to Machine Learning for Social Science Final Project
