remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: Yutong
description: The page of Yutong Quan's STATS201 Introduction to Machine Learning for Social Science Final Project
